baseURL: http://something-fresh.org/
publishDir: public
languageCode: en-us
title: flanksource
theme: hugo-fresh
enableInlineShortcodes: true
googleAnalytics: UA-157742796-1
#Disables warningss
disableKinds: -taxonomy
  -taxonomyTerm

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  description: flanksource is a niche consultancy focusing exclusively on Kubernetes and the Cloud Native ecosystem. We help companies navigate the CNCF landscape by evaluating and integrating technology into an infrastructure continuous delivery pipeline, tailored to each customer’s particular environment and stack.
  navbarlogo:
    # Logo (from static/images/logos/___)
    image: logos/logo_big.png
    link: /
  font:
    name: "Roboto"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: Kubernetes. Simplified.
    # Hero subtitle (optional)
    subtitle: We navigate the Cloud Native Landscape on your behalf - while wrapping it in tested Infrastructure Continuous  Delivery Pipeline.
    # Button text
    buttontext: Get in touch
    # Where the main hero button links to
    buttonlink: "/contact"
    # Hero image (from static/images/___)
    image: kubernetes_simple.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    #   - systek
    #   - tribe
    #   - kromo
    #   - infinite
    #   - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
    - title: Home
      url: /
    - title: About Us
      url: /about
    - title: Services
      url: /services
      sublinks:
        - title: Infrastructure Pipelines
          url: /infrastructure-pipelines
        # - title: Architecture & Strategy
        #   url: /
        - title: Platform Operations
          url: /platform-ops

    - title: Technology
      url: /technology
    - title: Open Source
      sublinks:
        - title: Konfigadm
          url: https://github.com/flanksource/konfigadm
        - title: Platform CLI
          url: https://github.com/flanksource/platform-cli
        - title: Image Builder
          url: https://github.com/kubernetes-sigs/image-builder
    - title: Blog
      url: /blog
    - title: Careers
      url: https://careers.flanksource.com
      button: true
  section1:
    title: Services
    subtitle:
    tiles:
      - title: Architecture & Strategy
        icon: kubernetes
        text: Embarking on your journey, or just need a production readiness assessment - we can help.
        url: /contact
        buttonText: Learn More
      - title: Platform Operations
        icon: team
        text: A dedicated team of experienced SRE's available 24x7, up-levelling your operational maturity.
        url: /platform-ops
        buttonText: Learn More
      - title: Infrastructure Pipelines
        icon: pipeline
        text: Custom CD pipelines for infrastructure that enable GitOps driven zero-touch deployments.
        url: /infrastructure-pipelines
        buttonText: Learn More
  # section2:
  #   title: You're here because you want the best
  #   subtitle: And we know it
  #   features:
  #     - title: Powerful and unified interface
  #       text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #       # Icon (from /images/illustrations/icons/___.svg)
  #       icon: laptop-globe
  #     - title: Cross-device synchronisation
  #       text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #       icon: doc-sync
  #     - title: Nomad system
  #       text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
  #       icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #     - name: Irma Walters
  #       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #       job: Accountant
  #       img: 1
  #     - name: John Bradley
  #       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #       job: Financial Analyst
  #       img: 2
  #     - name: Gary Blackman
  #       quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #       job: HR Manager
  #       img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: logo_big_128px_white.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      - link: https://github.com/flanksource
        # Icons are from Font Awesome
        icon: github

    bulmalogo: false
    quicklinks:
      column1:
        title: "About Us"
        links:
          - text: Values
            link: /about
          - text: Careers
            link: https://careers.flanksource.com
          - text: Contact Us
            link: /contact

      column2:
        title: "Services"
        links:
          - text: Infrastructure Pipelines
            link: /infrastructure-pipelines
          - text: Platform Operations
            link: /platform-ops

      column3:
        title: "Open Source"
        links:
          - text: konfigadm
            link: https://github.com/moshloop/konfigadm
          - text: cluster-api
            link: https://github.com/kubernetes-sigs/cluster-api
          - text: image-builder
            link: https://github.com/kubernetes-sigs/image-builder
